"""Adding picture column, post_user_oauth and get_user_oauth function in user models

Revision ID: 4ba05de7c8a4
Revises: 879c8f83516e
Create Date: 2022-07-27 20:13:51.612224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba05de7c8a4'
down_revision = '879c8f83516e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
