"""Adding google_id column in user table

Revision ID: 879c8f83516e
Revises: c155f588f438
Create Date: 2022-07-27 17:02:59.550190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879c8f83516e'
down_revision = 'c155f588f438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
