"""Add brand_name column in Record

Revision ID: c155f588f438
Revises: b2a1c3a14be1
Create Date: 2022-07-26 14:32:11.866583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c155f588f438'
down_revision = 'b2a1c3a14be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('brand_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'brand_name')
    # ### end Alembic commands ###
