"""change record tabble from nullable False to True

Revision ID: cc1c4f8b04b2
Revises: 87510fce9d30
Create Date: 2022-08-04 09:16:11.450728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc1c4f8b04b2'
down_revision = '87510fce9d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'register_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('record', 'log_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('record', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('record', 'serving_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('record', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('record', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('record', 'total_cals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('record', 'total_fat',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'total_fat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('record', 'total_cals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('record', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('record', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('record', 'serving_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('record', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('record', 'log_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('record', 'register_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
