"""Add calories goal and fat column

Revision ID: d9b75eac52a4
Revises: cc1c4f8b04b2
Create Date: 2022-08-14 12:48:27.668301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b75eac52a4'
down_revision = 'cc1c4f8b04b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cal_goal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fat_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fat_goal')
    op.drop_column('user', 'cal_goal')
    # ### end Alembic commands ###
