"""Create user and record models

Revision ID: f557c0f9811d
Revises: 
Create Date: 2022-08-16 12:57:05.711292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f557c0f9811d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login_id', sa.Text(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height_inches', sa.String(), nullable=True),
    sa.Column('weight_pound', sa.Integer(), nullable=True),
    sa.Column('cal_goal', sa.Integer(), nullable=True),
    sa.Column('fat_goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('record',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('serving_qty', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('total_cals', sa.Integer(), nullable=True),
    sa.Column('total_fat', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('user')
    # ### end Alembic commands ###
